services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $SOURCE_ROOT_DIR:$SOURCE_ROOT_DIR
      #By sharing the tmp folder with the host, we'll only donwload surprise's builtin datasets once per session
      - /tmp:/tmp
    tmpfs:
      - /home/$USER/.local
      - /home/$USER/.config
    environment:
      # Surprise's builtin datasets will be downloaded to SURPRISE_DATA_FOLDER
      - SURPRISE_DATA_FOLDER=/tmp/.surprise_data
      - PYTHONPATH=$SOURCE_ROOT_DIR:$SOURCE_ROOT_DIR/binaps/original/Binaps_code
    user: $UID:$GID
    working_dir: $SOURCE_ROOT_DIR
    entrypoint: jupyter-lab
    command: --no-browser --allow-root --notebook-dir=$SOURCE_ROOT_DIR --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --NotebookApp.token='something_secret'
    network_mode: host
  notebook-cuda:
    extends:
      service: notebook
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
