services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $BINAPS_ROOT_DIR:/workdir
    tmpfs:
      - /home/$USER
    user: $UID:$GID
    entrypoint: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/workdir
    network_mode: host
  notebook-cuda:
    build: .
    ports:
      - "8888:8888"
    runtime: nvidia
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - $BINAPS_ROOT_DIR:/workdir
    tmpfs:
      - /home/$USER
    user: $UID:$GID
    network_mode: host
    entrypoint: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/workdir
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
