FROM nvidia/cuda:11.0.3-base-ubuntu20.04

## Install Python
RUN apt update
RUN apt install -y python3 python3-pip

## Install basic data science libraries
# Required by the BinaPs implementation
RUN pip install numpy
RUN pip install scipy
RUN pip install pandas
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

# Install Jupyter and IPython support
RUN pip install jupyterlab
RUN pip install ipykernel
RUN pip install ipython
RUN python3 -m ipykernel install --name=binaps

## Install R
# To enable us to run binaps/Data/Synthetic_data/generate_toy.R
RUN DEBIAN_FRONTEND=noninteractive apt -y install r-base

# Install extension dependencies
RUN pip install rich
RUN pip install surprise
RUN pip install numba

# Data visualization dependencies
RUN pip install matplotlib
RUN pip install plotly
RUN pip install tabulate

# Unit test tooling
RUN pip install pytest
RUN pip install coverage
